# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d79d61427987551d201ef8a0a85210460c4985e7bc6377df79d98c3fe2edba5fbf40b7adea58fb34cd6416b9337ee6b7bced8b8ddb7b5ea0c4971910ecec04

test:
  secret_key_base: c6306aacb1dfa1ec040c7dfb7af62ccc1e293fe0531d01179d3be430c5cf0ed596b7e834d9d67b5cbfe5283013d27fc554005be18c56162171b970d9f30fdc1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
